#index:
#    path: /
#    controller: App\Controller\DefaultController::index

rule_engine:
  path: /rule-engine
  controller: App\Controller\RuleEngineController::index
  methods: [GET]

rule_engine_test:
  path: /rule-engine
  controller: App\Controller\RuleEngineController::test
  methods: [POST]
